### ISSUE TITLE
Depreciation warning - config.read() 

### ISSUE THREAD

**Issue by RhinosF1** [TheSandDoctor/redirect_maker#1]
config.read() on line 45 presents a depreciation warning advising that the code passed a bytesring as 'filenames'. This will not work in python 3. Use 'cp.read_file()' or switch to using Unicode strings across the board.

I'll email you a full screenshot.

**Comment by TheSandDoctor** [comment]
@RhinosF1 You are using python 3.6 I assume? If so, that warning is definitely interesting as it clearly does work using python 3. I have not encountered this issue myself before. What version of python are you using if it isn't 3.6?

**Comment by RhinosF1** [comment]
Believe it is still 2.7, I'll double check later as it's a new computer running on a linux terminal.

**Comment by TheSandDoctor** [comment]
All of my scripts were developed with python 3.6 in mind and the first line should have made it run with 3.6, but I see in the screenshot you sent that you were running it with the python command. Perhaps try just `chmod u+x ./redirect_maker.py` followed by `./redirect_maker.py` and see what happens?

**Comment by RhinosF1** [comment]
I'll try that later

**Comment by RhinosF1** [comment]
definitely using python 2.7.13
no change attempting to  use chmod

**Comment by TheSandDoctor** [comment]
@RhinosF1 Then please use 3.6, that is what the script is intended to run with

**Comment by RhinosF1** [comment]
Okay, can you give me support in the BRfA.

**Comment by TheSandDoctor** [comment]
@RhinosF1 BRFAs dont work that way. They are not a !vote.

**Comment by RhinosF1** [comment]
I understand but would it be possible to state you support the task, help it get through.
