### ISSUE TITLE
No option to override existing page block.

### ISSUE THREAD

**Issue by RhinosF1** [TheSandDoctor/redirect_maker#2]
Could an option be added where you can override an existing page with the bot's edits with manual approval as I accidently redirected all pages to my userspace rather than bot talkpage - bot userspace?

**Comment by TheSandDoctor** [comment]
@RhinosF1  I guess you could output to a file instead, but I am not sure I fully what you mean.

**Comment by RhinosF1** [comment]
Replace Line 20 with a input request for Y/N and add if Y override existing page content.. If N, don't change

**Comment by RhinosF1** [comment]
If you give me edit permission, I can comment the code where it's needed.

**Comment by TheSandDoctor** [comment]
@RhinosF1 the email confirmation link should be in your inbox from github shortly if it isn't already.

**Comment by RhinosF1** [comment]
Just commented changes in. Also commented out call home () as I don't use it due to it being ran when monitored by me.

**Comment by RhinosF1** [comment]
Have you had a chance to review changes.

**Comment by RhinosF1** [comment]
Fixed in Version 2
